name: Deployment Pipeline
env:
  BRANCH: master
  DEPLOY_REPO: https://github.com/arunv707/kubetest
  DEPLOY_BRANCH: new-env
  PACKAGE: ghcr.io/org-kubetest/migration-new
  DOCKERFILE: Dockerfile
  DEPLOY_PATH: /tmp/deploy
  KUBECONFIG: ${{secrets.KUBECONFIG}}
#on: workflow_dispatch
on: 
   workflow_dispatch:
   push:
    branches: [ master ]
jobs:
  build:
    name: Deployment
    runs-on: self-hosted
    steps:
    - name: Check out to branch
      uses: actions/checkout@v4
      with: 
        ref: ${{env.BRANCH}}
    - name: Login to ghcr.io
      uses: docker/login-action@v3 
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ${{env.DOCKERFILE}}
          push: true
          tags: |
            ${{env.PACKAGE}}:${{ github.sha }}
            ${{env.PACKAGE}}:latest
    - name: Setting up deployment yaml files
      run: |
        rm -rf $DEPLOY_PATH && git clone --branch $BRANCH $DEPLOY_REPO $DEPLOY_PATH
        sed -i "s/latest/$GITHUB_SHA/g" $DEPLOY_PATH/$BRANCH/deployment.yaml
        rm -rf $DEPLOY_PATH/$BRANCH/pod-autoscale.yaml
    - name: Applying yaml files
      run: |
        KUBECONFIG=$KUBECONFIG
        #kubectl apply -f $DEPLOY_PATH/$BRANCH/
    - name: Clean up
      run: |
        rm -rf $DEPLOY_PATH
        sudo docker rmi -f $(sudo docker images -q $PACKAGE:*)
