name: Deploy
on:
   push:
    branches: [ development ]
env:
  EKS_CLUSTER_NAME: NAD-SHARED-EKS-NLB
  AWS_REGION: ap-south-1
  KUBECONFIG: ${{secrets.KUBECONFIG}}
  DEPLOYMENT: ${{secrets.DEPLOYMENT}}
  PACKAGE: ghcr.io/techm-to-nad/000000000028210-nad-rmg-v2/development-new
  DOCKERFILE: Dockerfile.final
jobs:
  build:
    name: Deployment
    runs-on: self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v4
      with: 
        ref: development
    - name: Set up Environment
      run: |
        git_commit=$(git rev-parse HEAD)
        git_branch=$(git symbolic-ref --short HEAD)
        git_user=${{secrets.git_user}}
        git_user=${{secrets.git_token}}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3 
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push the image to GitHub Container Registry
      run: |
        # sudo docker login -u $git_user -p $git_token ghcr.io
        sudo docker build -t $PACKAGE:$git_commit -f $DOCKERFILE .
        sudo docker push $PACKAGE:$git_commit
        sudo docker tag $PACKAGE:$git_commit $PACKAGE:latest
        sudo docker push $PACKAGE:latest
        sudo docker rmi -f $PACKAGE:$git_commit
        sudo docker rmi -f $PACKAGE:latest
    - name: Injecting Commit ID to deployment.yaml
      run: |
        echo "$KUBECONFIG" > /tmp/kubeconfig
        echo "$DEPLOYMENT" > /tmp/deployment.yaml
        sed -i "s/latest/$git_commit/g" /tmp/deployment.yaml
    - name: Applying deployment.yaml
      run: |
        kubectl config current-context
        kubectl config use-context `~/kubectl config current-context`
        kubectl config current-context
        kubectl apply -f /tmp/deployment.yaml
    - name: Cleaning up
      run: rm -rf /tmp/kubeconfig /tmp/deployment.yaml
