name: Deploy to ECR
on:
  push:
    branches: [ master ]
env:
  ECR_REPOSITORY: kubetest
  EKS_CLUSTER_NAME: stg-m4marry-k8s
  AWS_REGION: ap-south-1
  KUBECONFIG: ${{secrets.MULTILINE}}
jobs:
  build:
    name: Deployment
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:

    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v2

    - name: testing
      env:
        MULTILINE: ${{env.KUBECONFIG}}
      run: |
        echo "$KUBECONFIG" > /tmp/kubeconfig
        cat /tmp/kubeconfig
        
