name: PRODUCTION DEPLOYMENT
env:
  # DEPLOY_REPO: https://${{ secrets.GH_PAT }}@github.com/techm-to-nad/000000000028210-NAD-RMG-V2-Deploy
  DEPLOY_BRANCH: new-env-prod
  DEPLOY_PATH: /tmp/deploy
  # KUBECONFIG: ${{secrets.KUBECONFIG_PROD}}
on:
   workflow_dispatch:
     inputs:
       commit_id:
         description: Commit ID of the image you want to deploy.
         required: true
         type: string
jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    # - name: Check out to branch
    #   uses: actions/checkout@v4
    #   with: 
    #     ref: ${{env.DEPLOY_BRANCH}}
    # - name: Login to ghcr.io
    #   uses: docker/login-action@v3 
    #   with:
    #       registry: ghcr.io
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GH_PAT }}
    - name: Setting up deployment yaml files
      run: |
        # rm -rf $DEPLOY_PATH && git clone --branch $DEPLOY_BRANCH $DEPLOY_REPO $DEPLOY_PATH
        mkdir -p $DEPLOY_PATH/$BRANCH/
        echo "something that changes:latest" > $DEPLOY_PATH/$BRANCH/deployment.yaml
        sed -i "s/latest/${{ inputs.commit_id }}/g" $DEPLOY_PATH/$BRANCH/deployment.yaml
        # rm -rf $DEPLOY_PATH/$BRANCH/pod-autoscale.yaml
    - name: Applying yaml files
      run: |
        cat $DEPLOY_PATH/$BRANCH/deployment.yaml
